name: Deploy WhatsApp Bot to Azure

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/whatsapp-AutoDeployTrigger.yml'

  workflow_dispatch: # Manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC auth with Azure
      contents: read

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Azure using federated identity
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.WHATSAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WHATSAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WHATSAPP_AZURE_SUBSCRIPTION_ID }}

      # Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}   # Code path
          containerAppName: whatsapp               # Your Container App name
          resourceGroup: DefaultResourceGroup-CCAN # Your resource group
          imageToBuild: whatsapp:${{ github.sha }} # Auto-builds image with Oryx
