name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Azure login
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3. Log in to ACR
      - name: Log in to ACR
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login registrybot123456.azurecr.io \
            -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      # 4. Build and push image
      - name: Build and push image
        run: |
          docker build -t registrybot123456.azurecr.io/whatsapp:${{ github.sha }} .
          docker push registrybot123456.azurecr.io/whatsapp:${{ github.sha }}

      # 5. Deploy to Container Apps
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: DefaultResourceGroup-CCAN
          containerAppName: registry123bot
          imageToDeploy: registrybot123456.azurecr.io/whatsapp:${{ github.sha }}
          registryUrl: registrybot123456.azurecr.io
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
