name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main   # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Azure login (Service Principal with JSON)
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Deploy from source code (no ACR, no Dockerfile)
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: DefaultResourceGroup-CCAN
          containerAppName: whatsapp
          sourcePath: .
